### ISSUE TITLE
Market Highlights

### ISSUE THREAD

**Issue by ghost** [RealToughCandy/project-ideas-for-web-developers#4]
Hey Everyone , This Abu Chowdhury Resident At Somewhere NJ USA. I work At Amazon as well as I'm a part time day Trader in Stock market. So yesterday I was Checking an Stock for And I was trying To check Everyday trading with Minute to minute for That I have to change lot of Chart in my brokerage account.. so I was feeling like how about If there is Apps giving market highlights of a every Stock I want with Minutes to Minute , day to Day Or Beginning to End. 
But I sample couldn't find anything with it. 
So I say myself that How about if I create A apps That that gives individual an Highlights of Stock with there needs ( Day To Day- Min to Min ) I know that's sound Crazy but I just wants to express my feeling. 

Sorry everyone if I messed with Your time 

@chowdabu

**Comment by RealToughCandy** [comment]
Thanks for the suggestion! We'll add it to the list sometime this week.

**Comment by RealToughCandy** [comment]
Added.
